language: rust
rust:
- stable
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - CARGO_TARGET=i686-pc-windows-gnu
    CARGO_FEATURES=
  - CARGO_TARGET=x86_64-pc-windows-gnu
    CARGO_FEATURES=
  global:
  - CARGO_QUIET=
  - CARGO_INCREMENTAL=0
  - secure: dQfrvMcAFSQNBVPsXebmOJUX6I5PVZ0I3I4lxCS+Ro9qdaDlYZBWLfBGW86KTrN5qUGCWP4yY80RHTLrJQUnczhKM3kAn0ct+41ca76iI9O43JQoSi9rQ/lSua2rEHztFTTIr4JIOXs30GEB6HFucaV7KBwHHtqRbHd8DbwN/lVC6BRRZ3ZAWA0pHuNX8LVWSW4hLYrdNInvfjYDdyQ2XbiIcb9/kcAqw+yDL8Q8cp7KPuJgvGRvDIiogJzsjBB+8YRzT+e6IsKrCiFHU3eN1wAbDHduE/0RpQ4oDkTAW6RiKxh9Xo1+wAWzwD6/feC7zId+N9IQ/VaeuoAtnGjNDaOHxFd/xVPGiLtPwrnPncXNQ9VplyARXXzDkedkRPnE2VFJvymfflK3sXOV0BeWjaa2oEGH+TRhSHeqjV8Pzq++jl0eT7SBDUxhv8aEDQjnQZ6oSM+sAk6WJfmHQxzMd+Veq7oFZNdDkQ2Pyjq7lhtl9e3649AltHpIcH3TzANDiYKXq4pX52iwKbJARSblwkkhGws3yktHsgSWVAq0U530K4ehnp0goswyCZDIxVfBJ/H2/XezY/nIZxOKuhDvGH+ZxGQXpEUdbbyJxv6v2dOOS+fpNjF2WLYa/YCYJsb+pwaex1XeUgcghEw2JfHWB+yUuCdgaeAiwQM24lgmlo8=
  - secure: YV3cHFyfIMbfUMi2xfq/TFAWlDBFTPGeFD7agfU1gNavfbzJ4RBFOo96P9cvGXuPKV/FD4rwGIKKKpUHj+8LhcfHoVM1ejX86sReY4w1CG0N9fv3Iw4ipZhX+kTAAiw2Gisqp9rub9zqCJrayvL6PguFkLrxQ/agLxeiQj5OUfZNpLPtehO9bBxhGsIW1P7GiKTIrQLf1lRFdLlX7rrhxdL8gENzJ2UQZknDah9rO0DakblgNf9iOScjpmzyMXYqvuozHIf5zKYicpkNvYyl2NDms0ij+u3OyJp7jy5r4ZiDjzKx8JcWOdPUmrW9DTt3Wb1g2b5UT7PXCyBexL3OgQL3m1U2+5NwpRGgqX6aZq6ycpEyfHVG58L7xsvgi66RaLgCDi5p5bHkzsb21kMDxVU3gOBRRio2DpHWlnaJNoGuLVj+jdL2R2a0epg8YEwlmBZ75630dEh/Eg3k2p3CqaXat686zsPW4u+rp/dTr9uED41+klQVUwZEhtUhSp4VbZL8gvVoQ4185vg2pG3T8Jc44vnZ8VygMRUF6QDytltbXSpNQuPRxBtAcQeSBPcC4FlO4bH39Q1GSseLYd8dKrbjW8wMvNZ90qRUA6yCi9VpXer57kBcoSSANFOxSjbtiUQwq7Kd9m6+LsGNKzQPXFoUgd0OPOjyqOH5AjSET/8=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.2.tar.gz | tar -xzC $HOME && . $HOME/ci-0.2/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable && $CARGO_TARGET = x86_64-pc-windows-gnu"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
